version: '3.9'

services:
  api:
    build: .
    container_name: digiwallet
    image: wallet
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:ro
    command: app.main:app --host 0.0.0.0 --reload
